version: "3"
services:
  python:
    container_name: python-env
    build: .
    volumes:
      - data:/usr/app/data
volumes:
  data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "./src/data"
